# language: haskell

env:
# - GHCVER=7.0.4
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.3
 - GHCVER=8.0.2
 - GHCVER=8.2.2
 - GHCVER=8.4.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install alex-3.1.7 happy-1.19.5 cabal-install-head ghc-$GHCVER
 - export PATH=/opt/cabal/head/bin:/opt/ghc/$GHCVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

install:
 - cabal update

script:
 - make sdist
 - cd dist
 - tar xvzf alex-*.tar.gz
 - cd alex-*/
 - "echo 'packages: .' > cabal.project"
 - cabal new-test --enable-tests
